name: bog-markdown-converter-build
on: [push]

jobs:
  build_npm:
    name: Build nodejs Application
    runs-on: ubuntu-latest
    steps:
       
    - name: setup-nodejs
      uses: actions/setup-node@v1
      # with:
      #   node-version: 12.x

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: build-app
      run: npm run build-pipeline

    # - name: echo-things
    #   run: echo '${{github.workspace}} - ${{github.run_id}} - ${{github.run_number}}'


  # Got this from https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages 
  build_docker:
    name: Publish docker image
    needs: [build_npm]
    if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

# These do not currently work for me, commenting out till I understand them more
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    - name: docker-login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker-push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: | 
          docker.pkg.github.com/${{ github.repository }}/bogmarkdownconverter:${{github.run_number}}
          docker.pkg.github.com/${{ github.repository }}/bogmarkdownconverter:latest
        
  
    # - name: publish-docker-image
    #   if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: "pirahawk"
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: pirahawk/bog-markdown-converter/bogmarkdownconverter
    #     tags: ${{github.run_number}},latest 