name: bog-markdown-converter-build
on: [push]

jobs:
  build_nuget:
    name: Build Converter Application
    runs-on: ubuntu-latest
    steps:
       
    - name: setup-nodejs
      uses: actions/setup-node@v1
      # with:
      #   node-version: 12.x

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: build-app
      run: npm run build-pipeline

    # - name: echo-things
    #   run: echo '${{github.workspace}} - ${{github.run_id}} - ${{github.run_number}}'