name: bog-markdown-converter-build
on: [push]

jobs:
  build_npm:
    name: Build nodejs Application
    runs-on: ubuntu-latest
    steps:
       
    - name: setup-nodejs
      uses: actions/setup-node@v1
      # with:
      #   node-version: 12.x

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: build-app
      run: npm run build-pipeline

    # - name: echo-things
    #   run: echo '${{github.workspace}} - ${{github.run_id}} - ${{github.run_number}}'

  build_docker:
    name: Publish docker image
    needs: [build_npm]
    if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'


    - name: Set up QEMU
      if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/setup-buildx-action@v1
    
    - name: docker-login
      if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: "pirahawk"
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: docker-push
      if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{github.run_number}},latest

    # - name: publish-docker-image
    #   if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: "pirahawk"
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: pirahawk/bog-markdown-converter/bogmarkdownconverter
    #     tags: ${{github.run_number}},latest 